package auction_server.service;

import auction_server.dao.AuctionDAO;
import auction_server.dao.BidTransactionDAO;
import auction_server.entities.Auction;
import auction_server.entities.BidTransaction;
import auction_server.entities.User;
import auction_server.behaviors.BidderProfile;

public class AuctionService {

    private final AuctionDAO auctionDAO = new AuctionDAO();
    private final BidTransactionDAO transactionDAO = new BidTransactionDAO();

    public void placeBid(Auction auction, User user, double bidAmount) {
        if (!user.hasRole(BidderProfile.class)) {
            throw new IllegalStateException("User must have a Bidder Profile to place bids.");
        }

        auction.getLock().lock();
        try {
            if (bidAmount <= auction.getCurrentHighestBid()) {
                throw new IllegalArgumentException("Bid amount must be higher than the current highest bid.");
            }
            if (user.equals(auction.getItem().getOwner())) {
                throw new IllegalArgumentException("Sellers cannot bid on their own items.");
            }

            // All checks passed, proceed with the bid
            auction.setCurrentHighestBid(bidAmount);

            // Create and save the transaction
            // The ID should be generated by the database, so we pass null.
            BidTransaction tx = new BidTransaction(null, auction, user, bidAmount);
            transactionDAO.save(tx);

            // Add to history and save the auction state
            auction.addTransaction(tx);
            auctionDAO.save(auction);

            System.out.println("New highest bid of " + bidAmount + " placed by " + user.getUsername() + " on item " + auction.getItem().getName());

        } finally {
            auction.getLock().unlock();
        }
    }

    public void closeAuction(Auction auction) {
        auction.getLock().lock();
        try {
            auction.setStatus("CLOSED");
            auctionDAO.save(auction);
            // TODO: Determine the winner and perform any final actions.
            // This could involve notifying the winner and seller.
            System.out.println("Auction for item " + auction.getItem().getName() + " is now closed.");
        } finally {
            auction.getLock().unlock();
        }
    }
}
